name: result_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  http: ^0.13.5
  loading_animation_widget: ^1.2.0+3
  google_sign_in: ^5.4.2
  aad_oauth: ^0.2.2
  jwt_decode_token: ^1.0.0
  email_otp: ^1.0.4
  dropdown_search: ^0.6.3
  intl: ^0.17.0
  multi_select_item: ^1.0.3
  country_state_city_picker: ^1.2.8
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  animated_splash_screen: ^1.3.0
  expandable: ^5.0.1
  d_chart: ^0.1.0
  group_radio_button: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  image_path: dev_assets/icon.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700